#command: bundle exec rails db:chatwoot_prepare


services:
  chatwoot-rails:
    image: chatwoot/chatwoot:v4.10.0

    environment:

      #configuracao SMTP
      MAILER_SENDER_EMAIL: Chat <rapjuve.escuadron.pastores@gmail.com>
      SMTP_DOMAIN: gmail.com
      SMTP_ADDRESS: smtp.gmail.com
      SMTP_PORT: "587"
      SMTP_USERNAME: rapjuve.escuadron.pastores@gmail.com
      SMTP_PASSWORD: sqlzuaeircdbmuun
      SMTP_AUTHENTICATION: login
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_OPENSSL_VERIFY_MODE: "peer"
      MAILER_INBOUND_EMAIL_DOMAIN: siemprecampeones.com
      
      RAILS_ENV: "production"
      NODE_ENV: "production"
      INSTALLATION_ENV: "docker"

      SECRET_KEY_BASE: "chave_unica"
      FRONTEND_URL: "https://chat.siemprecampeones.com"

      # Banco e Redis (caso estejam em outro compose ou serviços)
      POSTGRES_HOST: "postgres"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "minha_senha"
      POSTGRES_DATABASE: "chatwoot"
      REDIS_URL: "redis://redis:6379"
      #ACTIVE_STORAGE_SERVICE: local

      # Configurações S3/MinIO
      ACTIVE_STORAGE_SERVICE: "s3_compatible"
      STORAGE_BUCKET_NAME: "chatwoot"
      STORAGE_ACCESS_KEY_ID: "cP4nCeeMpsyk13r4TlQQ"
      STORAGE_SECRET_ACCESS_KEY: "FQTR51j6RNnTpIdJzBYSifgYnMGPLoe1PHZHnDNl"
      STORAGE_REGION: "us-east-1"
      STORAGE_ENDPOINT: "https://miniostorage.siemprecampeones.com"
      STORAGE_FORCE_PATH_STYLE: "true"
      AWS_REGION: "us-east-1"


      # Exemplo de chave OpenAI (opcional)
      #OPENAI_COMPLETIONS_ENABLED: "true"
      #OPENAI_API_KEY: ""

      # Logs
      RAILS_LOG_TO_STDOUT: "true"
      LOG_LEVEL: "info"
      CHATWOOT_HUB_URL: "https://chat.siemprecampeones.com/#"
      ENABLE_PUSH_RELAY_SERVER : "true"
      ENABLE_ACCOUNT_SIGNUP: "false"
      FIREBASE_PROJECT_ID: ""
      FIREBASE_CREDENTIALS: ""      

    networks:
      - app_network
    ports:
      - "3000:3000"
    volumes:
      - chatwoot_data:/app/storage
    restart: always
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  chatwoot-sidekiq:
    image: chatwoot/chatwoot:v4.10.0

    environment:
      #configuracao SMTP
      MAILER_SENDER_EMAIL: Chat <rapjuve.escuadron.pastores@gmail.com>
      SMTP_DOMAIN: gmail.com
      SMTP_ADDRESS: smtp.gmail.com
      SMTP_PORT: "587"
      SMTP_USERNAME: rapjuve.escuadron.pastores@gmail.com
      SMTP_PASSWORD: sqlzuaeircdbmuun
      SMTP_AUTHENTICATION: login
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_OPENSSL_VERIFY_MODE: "peer"
      MAILER_INBOUND_EMAIL_DOMAIN: siemprecampeones.com
      
      RAILS_ENV: "production"
      NODE_ENV: "production"
      INSTALLATION_ENV: "docker"

      SECRET_KEY_BASE: "chave_unica"
      FRONTEND_URL: "http://192.168.0.5:3000"

      POSTGRES_HOST: "postgres"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "minha_senha"
      POSTGRES_DATABASE: "chatwoot"
      REDIS_URL: "redis://redis:6379"
      #ACTIVE_STORAGE_SERVICE: local
      #Mesmas configs de MinIO/S3
      ACTIVE_STORAGE_SERVICE: "s3_compatible"
      STORAGE_BUCKET_NAME: "chatwoot"
      STORAGE_ACCESS_KEY_ID: "0XggPPlXeMJVsqoTblIz"
      STORAGE_SECRET_ACCESS_KEY: "cO8lTX9wKcn3NBGdp2itSoV7skeqnizQsbKIRgfZ"
      STORAGE_REGION: "us-east-1"
      STORAGE_ENDPOINT: "http://192.168.0.5:9002"
      STORAGE_FORCE_PATH_STYLE: "true"
      AWS_REGION: "us-east-1"

      #OPENAI_COMPLETIONS_ENABLED: "true"
      #OPENAI_API_KEY: ""

      RAILS_LOG_TO_STDOUT: "true"
      LOG_LEVEL: "info"
      CHATWOOT_HUB_URL: "https://chat.siemprecampeones.com/#"
      ENABLE_PUSH_RELAY_SERVER : "true"
      ENABLE_ACCOUNT_SIGNUP: "false"
      FIREBASE_PROJECT_ID: ""
      FIREBASE_CREDENTIALS: ""

    networks:
      - app_network
    volumes:
      - chatwoot_data:/app/storage
    restart: always
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

volumes:
  chatwoot_data:
networks:
  app_network:
    external: true